### ISSUE TITLE
Criar dropdown com tipos de utilizadores para admissões.

### ISSUE THREAD

**Issue by vascosilverio** [iptomar/Tech-Art-F#49]

**Comment by TiagoDCMorgado** [comment]
PR-> O mesmo dos comentarios https://github.com/iptomar/Tech-Art-F/pull/122/commits

SQL

`CREATE TABLE technart.admissoes_tipo (
	id INT auto_increment NOT NULL,
	descricao varchar(100) NULL,
	CONSTRAINT admissoes_tipo_pk PRIMARY KEY (id)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

insert into technart.admissoes_tipo (descricao)
values('Integrado'),
('Aluno'),
('Externo'),
('Colaborador')

ALTER TABLE technart.admissoes ADD tipo INT NULL ADD CONSTRAINT admissoes_admissoes_tipo_FK FOREIGN KEY (id) REFERENCES technart.admissoes_tipo(id);
`
